spring:
  application:
    name: shopapp

  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    username: root
    password:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

api:
  prefix: /api/v1
